const N='<a href="https://www.nist.gov/itl/ai-risk-management-framework" target="_blank" rel="noopener">NIST AI RMF</a> · <a href="https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence" target="_blank" rel="noopener">NIST GenAI Profile</a>';
const courseData={
evidence:{code:'EV-10',title:'Claims, Sources & Citations',minutes:55,summary:'Build a reproducible path from a generated claim to evidence a qualified reviewer can actually defend.',lessons:[
['Find the claims hiding in prose','Convert polished language into discrete propositions before evaluating it.',`<p>A sentence can hide several claims. “AI improves access to mental-health care” may assert increased availability, actual use, equitable reach, clinical benefit, and a causal relationship. Each needs different evidence.</p><p><strong>Method:</strong> circle the actor, action, population, comparison, outcome, place, and time. Label the result fact, inference, opinion, recommendation, or forecast. Rank it high, medium, or low consequence if wrong.</p>`,'A briefing says “automated intake reduces clinician burden and improves outcomes.”','Separate at least four claims: the intake is automated; clinician time or workload changed; patient outcomes changed; and automation caused the change. Do not evaluate the bundle as one claim.'],
['Match evidence to the proposition','Determine which source type can establish the exact proposition.',`<p>Authority depends on the question. Enacted text establishes what a statute says. A regulator explains its administration but may not resolve a court’s interpretation. A randomized study may estimate an intervention effect in its sample but not prove universal effectiveness.</p><p>Build an evidence hierarchy for the claim—not for the topic. Prefer original decisions, rules, standards, datasets, and reported results; use commentary to discover and contextualize them.</p>`,'A vendor blog links to a peer-reviewed study and says its product is “clinically validated.”','Open the study. Confirm the tested product/version, sponsor, population, comparator, endpoint, follow-up, attrition, effect size, uncertainty, and whether “clinical validation” is language the study supports.'],
['Read beyond the abstract','Test design, denominator, comparator, and limitations before repeating a result.',`<p>Ask who was included and excluded, how exposure and outcomes were defined, what the comparison actually was, whether missing data could change the result, and whether the analysis was prespecified. Relative change without the baseline can exaggerate practical importance.</p><p>Write both the supported claim and the strongest material limitation. If you cannot explain the denominator and comparator, you are not ready to publish the number.</p>`,'A study reports a 50% reduction, from 2 events per 10,000 to 1 per 10,000.','Report the absolute and relative change, timeframe, population, and uncertainty. “50% reduction” alone conceals the small baseline risk.'],
['Verify legal and policy claims','Check jurisdiction, authority, procedural status, effective date, and later history.',`<p>Distinguish a bill from enacted law, guidance from a binding rule, a trial ruling from controlling appellate authority, and publication from effectiveness. Track amendments, stays, appeals, repeals, corrections, and agency updates.</p><p>A reliable ledger records jurisdiction, issuing body, document type, identifier, date, effective status, pinpoint, and later treatment.</p>`,'A generated memo says “the state banned automated hiring decisions in 2025.”','Identify the state, instrument, covered decisions and entities, exceptions, effective date, implementing rules, enforcement, and current status. The sentence may be overbroad even if a relevant law exists.'],
['Use citations as evidence infrastructure','Create proposition-level citations another reviewer can reproduce.',`<p>Place a citation where its support is visible. Record title, issuer/author, stable identifier or URL, pinpoint, version, access date, and the proposition it supports. Archive permitted copies or metadata when link rot matters.</p><p>One citation at the end of a paragraph rarely supports every sentence. Never retain a plausible citation you have not opened.</p>`,'Three claims in one paragraph share one footnote to a 60-page report.','Create a claim-to-source table. Give each material proposition its own pinpoint or mark it unsupported. Narrow or remove anything the report does not establish.'],
['Write the verification record','Document the human judgment that turns research into defensible work product.',`<p>For each material claim record: exact wording, claim type, consequence of error, source, pinpoint, support summary, limitations, currency check, reviewer, date, and disposition—retain, narrow, qualify, remove, or escalate.</p><p>Close with unresolved uncertainty and the condition that would change the conclusion. Verification is complete when another qualified person can reproduce the path, not when the prose sounds convincing.</p>`,'A deadline arrives with two claims still unverified.','Do not silently publish. Remove them, label uncertainty with its decision impact, or escalate for an explicit risk decision. Record what remains open and who accepted it.']
],questions:[
['A statement contains actor, outcome, and causation. What comes first?',['Find one citation for the paragraph','Split it into separately testable propositions','Ask the model to sound less certain'],1,'Bundled claims require different evidence and should be separated before research.'],
['A vendor says its tool is clinically validated. Best first move?',['Repeat the peer-reviewed label','Open the study and test product, population, comparator, endpoint, and limits','Check the vendor’s follower count'],1,'Publication status alone does not establish fit between the study and the vendor claim.'],
['A 50% reduction from 2/10,000 to 1/10,000 should be reported as:',['Only 50%','Absolute and relative change with context','A clinically important result'],1,'Absolute baseline and uncertainty are necessary to interpret relative change.'],
['A bill introduced last month is:',['Enacted law','Evidence of a proposal, not enactment','Binding guidance'],1,'Procedural status is part of the legal proposition.'],
['One footnote after three factual sentences:',['Automatically supports all three','Requires proposition-level fit and pinpoints','Is always improper'],1,'Citation placement alone cannot replace support analysis.'],
['If a source cannot be opened:',['Keep it if plausible','Treat the proposition as unverified','Cite a search snippet'],1,'A citation you cannot inspect cannot complete verification.'],
['A limitation that changes applicability should be:',['Omitted for readability','Recorded and reflected in the claim','Moved to private notes only'],1,'Material limitations define the boundary of support.'],
['Verification is complete when:',['The prose sounds professional','A qualified reviewer can reproduce the claim-to-evidence path','The model gives confidence above 90%'],1,'Reproducibility—not fluency—is the completion standard.']
]},
privacy:{code:'PR-12',title:'Data Before Prompts',minutes:55,summary:'Decide what may enter an AI system before convenience turns into an unauthorized disclosure.',lessons:[
['Map the data and the duty','Identify the data, people, source, authority, and duties before choosing a tool.',`<p>Inventory direct identifiers, quasi-identifiers, communications, records, metadata, and inferred attributes. Ask who provided the information, for what purpose, under which notice, consent, policy, contract, privilege, or professional duty.</p><p>“Publicly available” is not a universal permission. Accuracy, context, terms, expectations, intellectual property, anti-discrimination rules, and reuse restrictions may still matter.</p>`,'A team wants to paste public employee biographies and internal performance notes into a ranking tool.','Treat the combined dataset as employment information. Identify decision purpose, authority, notice, discrimination risk, vendor handling, and whether the ranking is permitted—not merely whether biographies are public.'],
['Minimize and transform','Use the least information needed and choose the safest workable representation.',`<p>Remove fields unrelated to the task. Prefer synthetic records for design, aggregate data for trends, local processing where feasible, and tokenization or redaction when identifiers are unnecessary. Test whether combinations can re-identify someone.</p><p>Minimization reduces exposure; it does not create authority, eliminate bias, or make a prohibited use lawful.</p>`,'A contract summary needs payment dates but not party identities.','Use a verified local/redacted workflow containing only relevant clauses and dates. Preserve a secure mapping outside the AI tool only if the task truly requires it.'],
['Interrogate the actual product','Verify plan-specific retention, training, access, transfer, deletion, and security controls.',`<p>Consumer, team, enterprise, API, and embedded versions can have different terms. Record the exact service, plan, settings, contract version, subprocessors, storage regions, logging, training/reuse, administrative access, deletion mechanics, incident notice, and exit process.</p><p>A privacy toggle, marketing page, or model answer is not a complete technical and contractual assessment.</p>`,'A colleague says, “It is enterprise, so our data is private.”','Confirm the signed agreement, enabled settings, administrator configuration, subprocessors, retention, support access, training terms, and whether the proposed data category is approved.'],
['Separate privacy from confidentiality and security','Apply the right control to the right risk.',`<p>Privacy concerns appropriate processing of information about people. Confidentiality limits disclosure. Security protects systems and data. Privilege, trade-secret protection, records law, research rules, and professional ethics create additional layers.</p><p>Encryption can protect transit and storage while the use itself remains unauthorized. De-identification can reduce identifiability while the output still creates discriminatory effects.</p>`,'A tool encrypts all uploads but retains them indefinitely for product improvement.','Encryption does not answer purpose, reuse, retention, authority, or deletion. Evaluate each dimension separately.'],
['Use a proceed–escalate–stop gate','Translate uncertainty into an operational decision.',`<p><strong>Proceed</strong> only when purpose is authorized, data is minimized, the tool is approved, controls are known, and human responsibility is assigned. <strong>Escalate</strong> sensitive categories, new vendors, new purposes, cross-border transfers, vulnerable populations, or uncertain authority. <strong>Stop</strong> prohibited data, missing authority, or unacceptable access, reuse, retention, or inability to mitigate.</p>`,'A deadline is near and the vendor has not answered whether prompts are used for training.','Do not infer the answer. Use an approved alternative with synthetic or non-sensitive data, or stop and escalate. Urgency does not resolve authority.'],
['Document and revisit the decision','Create a data-use record that survives staff, vendor, and system changes.',`<p>Record purpose, owner, data categories, source and authority, minimization, tool/version/plan, contractual and technical controls, risk decision, approver, date, retention, deletion, and reassessment triggers.</p><p>Reassess when the use, population, data, model, vendor, integration, law, or policy changes. A prior approval is not a blanket license for function creep.</p>`,'An approved summarization tool adds memory and new third-party connectors.','Pause affected workflows until data flows, defaults, permissions, retention, and contract implications are reassessed and documented.']
],questions:[
['The first pre-prompt question is:',['Which model is fastest?','What data, authority, people, purpose, and duties are involved?','Can identifiers be shortened?'],1,'Classification and authority come before tool selection.'],
['Data minimization:',['Creates legal authority','Reduces unnecessary exposure but does not cure unauthorized use','Makes all data anonymous'],1,'Minimization is a safeguard, not permission.'],
['“Enterprise” alone proves:',['All proposed data is approved','Nothing without plan, configuration, and contract verification','No administrator can access data'],1,'Controls must be verified for the actual product and configuration.'],
['Encryption resolves:',['Security only, not every privacy or use question','All compliance questions','Authority to reuse data'],0,'A secure transfer can still support an unauthorized purpose.'],
['Unanswered training terms plus sensitive data should trigger:',['Proceed','Escalate or stop','A longer prompt'],1,'Unknown reuse is a decision-relevant uncertainty.'],
['Public information:',['May still carry context, accuracy, reuse, or rights constraints','Is always unrestricted','Can never be used'],0,'Public availability is only one part of the analysis.'],
['An approved tool adds memory and connectors. You should:',['Assume approval carries over','Reassess changed data flows and controls','Ignore features you do not click'],1,'Material system changes can alter exposure and authorization.'],
['A good data-use record includes:',['Only vendor name','Purpose, authority, data, controls, decision, owner, and triggers','Only a deletion date'],1,'A reproducible decision record captures the full use context.']
]},
governance:{code:'GV-15',title:'Human Oversight That Works',minutes:60,summary:'Turn “human in the loop” into decision rights, evidence thresholds, appeals, and operational accountability.',lessons:[
['Map the real decision','Identify where AI changes a person’s rights, access, resources, safety, or opportunity.',`<p>Trace inputs, model contribution, human action, downstream system, affected people, consequence, reversibility, and feedback loops. Distinguish brainstorming from ranking, recommendation from approval, and decision support from effective decision-making.</p><p>Risk lives in the sociotechnical system: incentives, staffing, policy, data, interfaces, and organizational use—not only the model.</p>`,'A model “only recommends” which benefit applications receive manual review first.','The recommendation allocates scarce review attention and can delay access. Map it as a consequential triage decision, including false negatives and appeal routes.'],
['Assign decision rights','Name who may use, review, override, escalate, pause, and approve.',`<p>Define accountable owner, qualified operator, independent reviewer where needed, incident lead, affected-person contact, and final approver. Give reviewers time, evidence, training, authority to disagree, and protection from automation pressure.</p><p>“A human reviews every output” is empty when that person lacks context, capacity, or power to change the result.</p>`,'A reviewer handles 600 flags per hour and may only click approve or reject.','The workflow creates automation bias and inadequate review capacity. Reduce volume, improve evidence access, permit escalation, measure overrides, and redesign the decision.'],
['Set evidence and release thresholds','Match validation and approval to consequence, uncertainty, and detectability.',`<p>Define prohibited uses, acceptable error boundaries, subgroup testing, security and privacy checks, source verification, stress cases, accessibility, fallback, rollback, and sign-off. Test the actual workflow, population, and version—not just a vendor benchmark.</p><p>High-impact uses require stronger independent evidence and safer defaults than reversible administrative assistance.</p>`,'A hiring model performs well overall but poorly for a small subgroup.','Do not average away the harm. Investigate data and workflow, evaluate lawful and fair use, test mitigations, and withhold or restrict release until the subgroup risk is acceptably addressed.'],
['Design explanation, contest, and remedy','Give affected people meaningful routes to understand and challenge consequential outcomes.',`<p>Provide usable notice of AI involvement, decision basis appropriate to context, a human contact, accessible contest process, timelines, evidence preservation, correction, and remedy. Monitor whether people can actually use the route.</p><p>An appeal that returns to the same automated logic without independent review is not meaningful contestability.</p>`,'A denied applicant may email support but receives only “the system was applied correctly.”','Provide the relevant basis, allow correction of erroneous inputs, assign qualified human reconsideration, track outcomes, and remedy improper delay or denial.'],
['Monitor operation and change','Detect drift, misuse, workarounds, unequal effects, and changed conditions.',`<p>Monitor performance, subgroup outcomes, overrides, complaints, appeals, near misses, incidents, latency, data shifts, and unauthorized uses. Define owners, frequency, thresholds, and automatic pause conditions.</p><p>Reassess after model, prompt, vendor, data, population, policy, integration, staffing, or purpose changes.</p>`,'Accuracy stays stable while human overrides fall to nearly zero.','Investigate automation bias, interface design, incentives, reviewer time, and whether disagreement is discouraged. Stable accuracy does not prove effective oversight.'],
['Respond and learn','Convert incidents into containment, accountability, repair, and verified improvement.',`<p>Protect people, contain the issue, preserve evidence, notify required functions, determine impact, analyze root and contributing causes, assign corrective actions, communicate appropriately, and verify the fix.</p><p>Include near misses and complaints. Close an incident only after the control is tested—not when a policy sentence is added.</p>`,'A model exposes confidential text in generated summaries.','Stop the affected workflow, preserve evidence, assess scope and notification duties, contain access, investigate data pathways, support affected people, fix controls, and verify against recurrence before restart.']
],questions:[
['A recommendation that controls review priority is:',['Merely administrative','A consequential allocation decision','Outside governance'],1,'Triage can change access and delay even without issuing the final decision.'],
['A reviewer processing 600 flags/hour demonstrates:',['Strong oversight','Possible capacity and automation-bias failure','Independent review'],1,'Human presence without time and authority is not effective control.'],
['Overall accuracy hides subgroup failure. Best response?',['Rely on the average','Investigate and restrict release until risk is addressed','Remove subgroup reporting'],1,'Aggregate performance cannot erase concentrated harm.'],
['Meaningful contestability includes:',['A generic support inbox only','Notice, relevant basis, correction, independent human review, and remedy','The same model rerunning the case'],1,'A challenge process must be usable and capable of changing the outcome.'],
['Overrides fall to zero. This may indicate:',['Perfect automation','Automation bias or constrained reviewers','No monitoring need'],1,'Override patterns are operational evidence requiring investigation.'],
['A vendor benchmark proves readiness for your workflow:',['Yes','No—contextual validation is still required'],1,'Release evidence must fit the actual use, population, and version.'],
['An incident closes when:',['A policy is updated','Corrective controls are implemented and verified','Public attention ends'],1,'Verification of the fix is part of closure.'],
['Governance applies to:',['The model only','The full sociotechnical decision system','Only high-risk vendors'],1,'People, policy, interfaces, data, incentives, and downstream actions shape risk.']
]}};
const param=new URLSearchParams(location.search).get('course'),id=courseData[param]?param:'evidence',c=courseData[id],key='myelin-'+c.code.toLowerCase()+'-v2';document.title=c.code+' · '+c.title+' | Myelin';document.querySelectorAll('[data-id]').forEach(a=>a.classList.toggle('active',a.dataset.id===id));meta.textContent=`${c.code} · 6 lessons · approximately ${c.minutes} minutes`;title.textContent=c.title;summary.textContent=c.summary;let state={lessons:Array(6).fill(false),attempts:[],passed:false,notes:{}};try{state={...state,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{}
function save(){const pass=[...state.attempts].reverse().find(a=>a.score>=7);if(pass&&state.lessons.every(Boolean)&&!state.passed){state.passed=true;state.completedAt=new Date().toISOString();state.recordId='MY-'+c.code+'-'+crypto.randomUUID().slice(0,8).toUpperCase()}localStorage.setItem(key,JSON.stringify(state));render()}
function render(){lessons.innerHTML=c.lessons.map((l,i)=>`<article class="lesson"><div class="eyebrow">Lesson ${i+1} of 6</div><h2>${l[0]}</h2><p class="objective"><strong>Objective:</strong> ${l[1]}</p>${l[2]}<details><summary><strong>Apply it: ${l[3]}</strong></summary><label for="note${i}">Write your decision before revealing the model response.</label><textarea id="note${i}" data-note="${i}" rows="4" style="width:100%;padding:.7rem;margin:.6rem 0" placeholder="Your reasoning stays in this browser.">${state.notes[i]||''}</textarea><details><summary>Reveal a defensible response</summary><p class="source">${l[4]}</p></details></details><p class="source"><strong>Framework:</strong> ${N}</p><label><input type="checkbox" data-i="${i}" ${state.lessons[i]?'checked':''}> I completed the lesson and scenario.</label></article>`).join('');document.querySelectorAll('[data-i]').forEach(x=>x.onchange=()=>{state.lessons[+x.dataset.i]=x.checked;save()});document.querySelectorAll('[data-note]').forEach(x=>x.onchange=()=>{state.notes[x.dataset.note]=x.value;localStorage.setItem(key,JSON.stringify(state))});let n=state.lessons.filter(Boolean).length;progressText.textContent=`${n} of 6 lessons complete`;bar.style.width=n/6*100+'%';let last=state.attempts.at(-1);result.textContent=last?`Latest: ${last.score}/8 · ${last.score>=7?'mastery met':'review feedback and retry'} · ${state.attempts.length} attempt(s)`:'';record.classList.toggle('show',state.passed);if(state.passed){recordTitle.textContent=c.code+' completed';completed.textContent=new Date(state.completedAt).toLocaleString();score.textContent=(state.attempts.findLast(a=>a.score>=7)?.score||7)+'/8';recordId.textContent=state.recordId}}
quiz.innerHTML=c.questions.map((q,i)=>`<fieldset><legend>${i+1}. ${q[0]}</legend>${q[1].map((a,j)=>`<label class="answer"><input required type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}<p id="fb${i}" aria-live="polite"></p></fieldset>`).join('');
quiz.onsubmit=e=>{e.preventDefault();let f=new FormData(quiz),s=0;c.questions.forEach((q,i)=>{let ok=Number(f.get('q'+i))===q[2];s+=ok;let el=document.getElementById('fb'+i);el.textContent=(ok?'Correct. ':'Review: ')+q[3];el.style.color=ok?'#256448':'#993b2c'});state.attempts.push({score:s,at:new Date().toISOString()});save();if(s>=7&&!state.lessons.every(Boolean))result.textContent='Mastery met. Complete all six lesson scenarios to unlock the record.'};
printBtn.onclick=()=>print();exportBtn.onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({schema:'myelin-noncredit-record',version:2,course:c.code,credit:0,...state},null,2)],{type:'application/json'}));a.download=c.code.toLowerCase()+'-record.json';a.click()};deleteBtn.onclick=()=>{if(confirm('Delete this course’s progress, notes, and attempts?')){localStorage.removeItem(key);location.reload()}};render();
